# This is a REFERENCE COPY of the aws-auth ConfigMap
# The actual ConfigMap is managed in the kube-system namespace
# This file is for documentation and disaster recovery

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::899630542737:role/project-bedrock-cluster-node-role
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::899630542737:user/bedrock-dev-view
      username: bedrock-dev-view
      groups:
        - view
