apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bedrock-dev-view-binding
  labels:
    app: bedrock
    role: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: User
    name: arn:aws:iam::899630542737:user/bedrock-dev-view
    apiGroup: rbac.authorization.k8s.io
